"""Email event history endpoints."""

import uuid
from datetime import datetime

from fastapi import APIRouter, Depends
from pydantic import BaseModel, ConfigDict
from sqlalchemy.orm import Session

from app.api.deps import get_current_user
from app.core.database import get_db
from app.models.draft import Draft
from app.models.email_event import EmailEvent

router = APIRouter()


class EmailEventOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    sender_email: str
    subject: str
    summary_text: str | None
    created_at: datetime


class DraftOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    generated_draft: str | None
    model_name: str
    token_input: int
    token_output: int
    estimated_cost: float
    created_at: datetime


class EmailEventWithDraft(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    sender_email: str
    subject: str
    summary_text: str | None
    created_at: datetime
    drafts: list[DraftOut] = []


@router.get("/", response_model=list[EmailEventOut])
async def list_email_events(
    limit: int = 20,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Return the most recent email events for the current tenant."""
    tenant_id = current_user.get("tenant_id")
    events = (
        db.query(EmailEvent)
        .filter(EmailEvent.tenant_id == tenant_id)
        .order_by(EmailEvent.created_at.desc())
        .limit(limit)
        .all()
    )
    return events


@router.get("/drafts", response_model=list[DraftOut])
async def list_drafts(
    limit: int = 20,
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Return the most recent drafts generated by the current tenant."""
    tenant_id = current_user.get("tenant_id")
    drafts = (
        db.query(Draft)
        .filter(Draft.tenant_id == tenant_id)
        .order_by(Draft.created_at.desc())
        .limit(limit)
        .all()
    )
    return drafts


@router.get("/usage")
async def get_usage(
    current_user: dict = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Return total drafts generated and tokens used for the current tenant."""
    tenant_id = current_user.get("tenant_id")
    from sqlalchemy import func

    result = db.query(
        func.count(Draft.id).label("total_drafts"),
        func.sum(Draft.token_input).label("total_tokens_in"),
        func.sum(Draft.token_output).label("total_tokens_out"),
        func.sum(Draft.estimated_cost).label("total_cost"),
    ).filter(Draft.tenant_id == tenant_id).first()

    return {
        "total_drafts": result.total_drafts or 0,
        "total_tokens_in": result.total_tokens_in or 0,
        "total_tokens_out": result.total_tokens_out or 0,
        "total_cost_usd": round(result.total_cost or 0, 6),
    }
